#!/bin/sh
X=#_G--[[
exec lua -i "$0" "$@"
--]] X=nil

l=require 'ljcurses'

do
   local errmsg
   function with_curses(fn, ...)
      if not errmsg then
	 l.init_curses()
	 if l.start_color() then
	    l.refresh()
	    fn(...)
	 else
	    errmsg='\nYou need a color terminal to do this!'
	 end
	 l.endwin()
      end
      print(errmsg or '')
   end
end

a=l.attributes
b=l.boxes

--[[
local function testfn()
   l.init_pair(1, a.white, a.blue)
   l.init_pair(2, a.red, a.black)
   l.init_pair(3, a.yellow, a.black)
   l.addnstr('This is ', 40)
   l.attron(bit.bor(l.color_pair(1),a.bold))
   l.addnstr('colorful', 40)
   l.attroff(l.color_pair(1))
   l.attron(l.color_pair(2))
   l.addnstr('!!!', 13)
   l.attroff(l.color_pair(2))
   w2 = l.newwin(12,12,4,4)
   l.box(w2,b.vline,b.hline)
   l.noutrefresh(w2)
   w = l.newwin(10,10,5,5)
   l.bkgd(w,l.color_pair(3))
   l.move(w, 0,0)
   l.addstr(w,'hello thingies')
   l.noutrefresh(w)
   l.doupdate()
   l.getch()
   l.refresh(nil)
end

local function testfn2()
   l.noutrefresh(nil)
   l.move(w2, 0, 0)
   l.clrtobot(w2)
   l.noutrefresh(w2)
   l.redrawwin(w)
   l.noutrefresh(w)
   l.doupdate()
   l.getch()
   l.refresh(nil)
end

local function testfn3()
   l.noutrefresh(nil)
   l.noutrefresh(w2)
   l.move(w,0,0)
   l.clrtobot(w)
   l.noutrefresh(w)
   l.doupdate()
   l.getch()
   l.refresh(nil)
end

with_curses(testfn)

with_curses(testfn2)

with_curses(testfn3)
--]]

function tooctal(num)
   local output=''
   while num > 0 do
      output = ''..(num % 8)..output
      num = (num - num % 8)/8
   end
   return '0'..output
end

key_name = {}

for name,_ in pairs(l.keys) do
   key_name[l.keys[name]] = name
end

with_curses(function ()
      repeat
	 k=l.getch()
	 l.addstr((key_name[k] or tooctal(k))..' ')
      until k==32 end)

os.exit(0)
