#!/bin/bash
dummy= #_G and nil --[[
   script=$(readlink -f "$0")
   origin=${script%/*}
   completions=/dev/null
   [ -f $origin/completions ] && completions=$origin/completions
   exec rlwrap -b ":(){}[],+-=&^%$#@\"';|\\"  \
	       -f $completions		     \
	       -c -H $HOME/.${script##*/}_history \
	       lua "$script" "$@"
--]]

local origin=(arg and (arg[0]:match '^(.*)/') or '.')

package.path=origin..'/?.lua'..';'..package.path
package.cpath=origin..'/?.so'..';'..package.cpath
require 'util'
require 'elfutil'
marshal=require 'freezer'
require 'ljcurses'
require 'cpiofns'
require 'utilfns'
require 'resolver'
require 'tagfile'
require 'editor'
bad_offers = require 'bad_offers'
pp=require 'pprint'
function pt(t,l) io.write(pp.pformat(t, {depth_limit = l or 1}),'\n') end
if arg[1] == '-h' then
   print('Usage: '..arg[0]..' savefile...')
   os.exit(0)
end
print 'Welcome to the Slackware Tagfile Tool'
sf={}
for ix, savefile in ipairs(arg) do
   sf[ix] = reconstitute(savefile)
   print(('Reading save file %s into sf[%d].'):
	 format(savefile:match '([^/]*)$', ix))
end


-- Local Variables:
-- mode: lua
-- End:
